services:
  python_api:
    build:
      context: ./
      dockerfile: ./backend.Dockerfile
    env_file: .env
    restart: always
    container_name: python_api
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/usr/src/app/
    depends_on:
      - postgres_db



  postgres_db:
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    ports:
      - '5432:5432'